server {
  server_tokens off;
  client_max_body_size 50M;
  server_name $OVERLEAFURL;
  location / {
    proxy_pass http://overleaf:8889;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection \"upgrade\";
    proxy_set_header Host \$host;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_read_timeout 3m;
    proxy_send_timeout 3m;
  }

  listen [::]:443 ssl ipv6only=on proxy_protocol;
  listen 443 ssl proxy_protocol;
  ssl_certificate /etc/letsencrypt/live/$HOSTNAME/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/$HOSTNAME/privkey.pem;
  # Load the Diffie-Hellman parameter.
  ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

  # Define the ciphers to use in the preferred order.
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers \"EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED\";
}

server {
  if (\$host = $OVERLEAFURL) {
    return 301 https://\$host\$request_uri;
  } # managed by Certbot
  listen [::]:80 ipv6only=on proxy_protocol;
  listen 80 proxy_protocol;
  server_name $OVERLEAFURL;
  return 404;
}