services:
  cloud:
    depends_on:
      - cloud_db
    container_name: cloud
    image: nextcloud:32.0.5-fpm
    networks:
      - front_tier
      - back_tier
    env_file:
      - .env.nextcloud
    volumes:
      - cloud_full:/var/www/html
      - cloud_full:/var/www/nextcloud
  cloud_db:
    container_name: cloud_db
    image: mariadb:12.1.2-noble
    env_file:
      - .env.nextcloud
    networks:
      - back_tier
    volumes:
      - cloud_db_data:/var/lib/mysql
      - cloud_db_backups:/backups
volumes:
  cloud_db_backups:
  cloud_db_data:
  cloud_full:
