services:
  trilium:
    container_name: trilium
    image: triliumnext/trilium:latest
    restart: unless-stopped
    networks:
      - front_tier
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    volumes:
      - ../conf/trilium:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
