services:
  frp:
    image: ghcr.io/brucekomike/frp-ct-server:latest
    #image: snowdreamtech/frpc:trixie
    env_file:
      - .env.frp
    volumes:
      - ../conf/frp:/etc/frp
    networks:
      - frp