services:
  gitlab:
    image: gitlab/gitlab-ce:18.6.4-ce.0
    container_name: gitlab
    restart: always
    hostname: '${GITLAB_DOMAIN}'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url '${GITLAB_URL}'
        nginx['enable'] = false
        web_server['external_users'] = ['www-data']
        gitlab_rails['trusted_proxies'] = [ '192.168.0.0/24' ]
        

    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'