services:
  keycloak:
    image: keycloak/keycloak:latest
    container_name: keycloak
    env_file:
      - .env.keycloak
    networks:
      - back_tier
      - front_tier
  keycloak_db:
    image: postgres:latest
    container_name: keycloak_db
    env_file:
      - .env.keycloak
    networks:
      - back_tier
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
volumes:
  keycloak_db_data: