services:
  mediawiki-fpm:
    container_name: wiki
    image: ossmediawiki:1.45.1
    networks:
      - front_tier
      - back_tier
    env_file:
      - .env.mediawiki
    volumes:
      - mediawiki_uploads:/var/www/html/images
  wiki_db:
    container_name: wiki_db
    image: mariadb:12.1.2-noble
    env_file:
      - .env.mediawiki
    networks:
      - back_tier
    volumes:
      - mariadb_data:/var/lib/mysql
      - mariadb_backups:/backups
volumes:
  mariadb_backups:
  mariadb_data:
  mediawiki_localsettings:
  mediawiki_uploads: