services:
  nginx:
    image: nginx:trixie
    container_name: nginx
    volumes:
      - ../conf/nginx:/etc/nginx/conf.d
      - mediawiki_full:/var/www/mediawiki
      - cloud_full:/var/www/nextcloud
    networks:
      - front_tier
      - frp
    ports:
      - "80:80"
networks:
  front_tier:
    driver: bridge
  frp:
    driver: bridge
  back_tier:
    driver: bridge