services:
  nginx:
    image: nginx:trixie
    volumes:
      - ../conf/nginx:/etc/nginx/conf.d
    networks:
      - front_tier
      - frp
    ports:
      - "80:80"
networks:
  front_tier:
    driver: bridge
  frp:
    driver: bridge
  back_tier:
    driver: bridge