services:
  wiki:
    container_name: wiki
    image: ossmediawiki:1.45.1-fpm
    networks:
      - front_tier
      - back_tier
    env_file:
      - .env.mediawiki
    volumes:
      - mediawiki_uploads:/var/www/html/images
      - mediawiki_full:/var/www/html
      - mediawiki_full:/var/www/mediawiki
      # place your wiki config into the coresponding folder and uncomment the line below
      #- ../conf/wiki/LocalSettings.php:/var/www/html/LocalSettings.php:ro
  wiki_db:
    container_name: wiki_db
    image: mariadb:12.1.2-noble
    env_file:
      - .env.mediawiki
    networks:
      - back_tier
    volumes:
      - wiki_db_data:/var/lib/mysql
      - wiki_db_backups:/backups
volumes:
  wiki_db_backups:
  wiki_db_data:
  mediawiki_localsettings:
  mediawiki_uploads:
  mediawiki_full:
