server { 
	server_name $DOCURL;
	location = /robots.txt {
		add_header  Content-Type  text/plain;
		return 200 \"User-agent: *\nDisallow: /\n\";
	}
	root /var/www/docs/$DOCNAME/html-docs;
    index index.html index.htm index.nginx-debian.html;
	location / {
		try_files \$uri \$uri/ =404;
		auth_basic \"password required\";
		auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
	}

	listen [::]:443 ssl;
	listen 443 ssl;
	ssl_certificate /etc/letsencrypt/live/$HOSTNAME/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/$HOSTNAME/privkey.pem;
	# Load the Diffie-Hellman parameter.
	ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

	# Define the ciphers to use in the preferred order.
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;
	ssl_ciphers \"EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:DHE+AESGCM:DHE:!RSA!aNULL:!eNULL:!LOW:!RC4:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!CAMELLIA:!SEED\";
}

server {
	if (\$host = $DOCURL ) {
		return 301 https://\$host\$request_uri;
	}
	server_name $DOCURL;
	listen [::]:80;
	listen 80;
  return 404;
}