server { 

	server_name $DOCURL;
	location = /robots.txt {
		add_header  Content-Type  text/plain;
		return 200 \"User-agent: *\nDisallow: /\n\";
	}
	root /var/www/$DOCNAME;
    index index.html index.htm index.nginx-debian.html;
	location / {
		try_files \$uri \$uri/ =404;
		auth_basic \"password required\";
		auth_basic_user_file /etc/nginx/conf.d/.htpasswd;
	}

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/$HOSTNAME/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$HOSTNAME/privkey.pem;
    #ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;
}

server {
    if (\$host = $DOCURL ) {
        return 301 https://\$host\$request_uri;
    }
	server_name $DOCURL;
	listen 80;
    return 404;
}